function setProfileFields() {
	var fieldNames = [ 
		"parish",
		"city",
		"vkd_leadershipDate",
		"vkd_advancedGiftsDate",
		"vkd_specialGiftsDate",
		"vkd_generalGiftDate",
		"vkd_commitmentWeekendDates",
		"vkd_leadershipNumberFamilies",
		"vkd_advancedGiftsNumberFamilies",
		"vkd_specialGiftsNumberFamilies",
		"vkd_generalGiftsNumberFamilies",
		"vkd_leadershipVolunteersNeeded",
		"vkd_advancedGiftsVolunteersNeeded",
		"vkd_specialGiftsVolunteersNeeded",
		"vkd_leadershipCECOrientation",
		"vkd_advancedGiftsPhaseOrientation",
		"vkd_generalGiftsVolunteersNeeded",
		"vkd_specialGiftsSpecialTraining",
		"vkd_specialGiftsPhoneathonOrientation",
		"vkd_generalGiftPhoneAThon",
		"vkd_commitmentWeekend1Date",
		"vkd_commitmentWeekend2Date",
		"parishHistory",
		"caseNeed1",
		"caseNeed2",
		"caseNeed3",
		"caseNeed4",
		"caseNeed5",
		"parishGoal",
		"parishShare",
		"pastorInf",
		"campaignType",
		"AOBGoal",
		"surplusShare",
		"caseElement1",
		"ce1estimatedCost",
		"ce2estimatedCost",
		"ce1details1",
		"ce1details2",
		"ce1details3",
		"caseElement2",
		"ce2details1",
		"ce2details2",
		"ce2details3",
		"caseElement3",
		"ce3estimatedCost",
		"ce3details1",
		"ce3details2",
		"ce3details3",
		"caseElement4",
		"ce4estimatedCost",
		"ce4details1",
		"ce4details2",
		"ce4details3",
		"caseElement5",
		"ce5estimatedCost",
		"ce5details1",
		"ce5details2",
		"ce5details5",
		"potentialMembersDate",
		"oc_generalCampaignChair1",
		"oc_generalCampaignChair2",
		"oc_majorGiftsChair1",
		"oc_majorGiftsChair2",
		"oc_advancedGiftsChair1",
		"oc_advancedGiftsChair2",
		"oc_specialGeneralGiftsChair1",
		"oc_specialGeneralGiftsChair2",
		"oc_recruitmentChair1",
		"oc_recruitmentChair2",
		"oc_recruitmentChair3",
		"oc_recruitmentChair4",
		"oc_campaignSecretary",
		"firstNameLastName",
		"parishID",
		"pastorFormal"
	];
	var user_id = CallSINIMethod("GetValue", ["SystemProperty", "LoggedOnUserID", null]);

	for(var i=0; i < fieldNames.length; i++) {
		var setValue = FormGetFieldValue(fieldNames[i]);
		var profileField = fieldNames[i] + 'PF';
		var userProfileField = CallSINIMethod("SetValue", ["UserField", profileField, user_id, setValue]);
	}
}